# Site settings
title: Dirk Dittmar
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Blog und Galerie von Dirk Dittmar. Der Blog eines Java-Enterprise-Web-Software-Developers und die Galerie eines ambitioniert Amateur-Fotographen.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ddittmar.github.io" # the base hostname & protocol for your site
twitter_username: dittma_d
github_username:  ddittmar

# Build settings
markdown: kramdown
permalink: /blog/:categories/:year/:month/:day/:title/
highlighter: pygments
gems:
  - jekyll-sitemap
  - jemoji
