#!/bin/bash
find js/ -iname "*.js" | grep -v '\.min\.js$' | while read file; do
    minfile=`echo "$file" | sed -r 's/^(.*)\.js/\1\.min\.js/g'`
    echo "$file -> $minfile"
    java -jar compiler.jar --js $file > $minfile
done
